name: Pages

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.21.6'

            - name: Build
              run: GOOS=js GOARCH=wasm go build -o wasm/build/main.wasm wasm/main.go

            - name: Copy WASM runtime
              run: cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" wasm/

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'

            - name: Install dependencies
              run: cd wasm && npm ci && npm run build && cd ..

            - name: Upload static files as artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                path: wasm/
    deploy:
        needs: build

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4
